name: Build and Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.sha.outputs.short_sha }}
    steps:
      - name: Calculate short SHA
        id: sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    uses: pauloo27/deployment-workflows/.github/workflows/docker-build-push.yml@main
    with:
      image: ghcr.io/pauloo27/sample-java-api
      tag: ${{ needs.prepare.outputs.short_sha }}
    permissions:
      contents: read
      packages: write

  deploy:
    needs: [prepare, build]
    uses: pauloo27/deployment-workflows/.github/workflows/helm-install.yml@main
    with:
      release_name: sample-java-api
      chart: oci://ghcr.io/pauloo27/helm-charts/sample-java-api:v0.1.1
      namespace: dev
      image_tag: ${{ needs.prepare.outputs.short_sha }}
      values_file: ./helm/values.dev.yml
    secrets:
      kubeconfig: ${{ secrets.KUBECONFIG }}
      openvpn_config: ${{ secrets.OPENVPN_CONFIG }}

